import React, { useContext } from 'react'
import { ResumeInfoContext } from '@/context/ResumeInfoContext';

function FreeformPreview() {
    const {resumeInfo} = useContext(ResumeInfoContext);
    
    return (
        <div className='shadow-lg h-full p-14 border-t-[20px] bg-white text-black min-h-[800px]'
            style={{ borderColor: resumeInfo?.themeColor || '#5b3fd9' }}
        >
            <div 
                className="resume-html-content"
                style={{
                    lineHeight: '1.6',
                    fontSize: '14px',
                }}
                dangerouslySetInnerHTML={{ __html: resumeInfo?.content || '<i>Empty resume content</i>' }} 
            />
            {/* Inline styles for basic HTML elements generated by markdown */}
            <style dangerouslySetInnerHTML={{__html: `
                .resume-html-content h1 { font-size: 24px; font-weight: bold; margin-bottom: 12px; border-bottom: 2px solid ${resumeInfo?.themeColor || '#5b3fd9'}; padding-bottom: 4px; }
                .resume-html-content h2 { font-size: 20px; font-weight: bold; margin-top: 16px; margin-bottom: 8px; color: ${resumeInfo?.themeColor || '#5b3fd9'}; }
                .resume-html-content h3 { font-size: 16px; font-weight: bold; margin-top: 12px; margin-bottom: 4px; }
                .resume-html-content ul { list-style-type: disc; margin-left: 20px; margin-bottom: 12px; }
                .resume-html-content p { margin-bottom: 12px; }
                .resume-html-content table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
                .resume-html-content th, .resume-html-content td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                .resume-html-content th { background-color: #f2f2f2; }
            `}} />
        </div>
    )
}

export default FreeformPreview;
